//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhTDSE62847_Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHoaDon
    {
        public int soHoaDon { get; set; }
        public string maSach { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string ghiChu { get; set; }
        public bool hieuLuc { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblSach tblSach { get; set; }
    }
}
