//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhTDSE62847_Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        public tblHoaDon()
        {
            this.tblChiTietHoaDons = new HashSet<tblChiTietHoaDon>();
        }
    
        public int soHoaDon { get; set; }
        public Nullable<System.DateTime> ngayLapHD { get; set; }
        public string maDaiLy { get; set; }
        public bool hieuLuc { get; set; }
    
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public virtual tblDaiLy tblDaiLy { get; set; }
    }
}
