//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhTDSE62847_Final_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLySachDBEntities : DbContext
    {
        public QuanLySachDBEntities()
            : base("name=QuanLySachDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public DbSet<tblDaiLy> tblDaiLies { get; set; }
        public DbSet<tblDangNhap> tblDangNhaps { get; set; }
        public DbSet<tblHoaDon> tblHoaDons { get; set; }
        public DbSet<tblNhaXB> tblNhaXBs { get; set; }
        public DbSet<tblSach> tblSaches { get; set; }
    }
}
