//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhTDSE62847_Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDangNhap
    {
        public string username { get; set; }
        public string password { get; set; }
        public bool isAdmin { get; set; }
    }
}
