//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhTDSE62847_Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhaXB
    {
        public tblNhaXB()
        {
            this.tblSaches = new HashSet<tblSach>();
        }
    
        public string maNhaXB { get; set; }
        public string tenNhaXB { get; set; }
        public string diaChi { get; set; }
        public string dienThoai { get; set; }
        public bool cungCap { get; set; }
    
        public virtual ICollection<tblSach> tblSaches { get; set; }
    }
}
