//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhTDSE62847_Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSach
    {
        public tblSach()
        {
            this.tblChiTietHoaDons = new HashSet<tblChiTietHoaDon>();
        }
    
        public string maSach { get; set; }
        public string tenSach { get; set; }
        public string tenTacGia { get; set; }
        public string giaBia { get; set; }
        public string giaBanChoDaiLy { get; set; }
        public string maNhaXB { get; set; }
        public Nullable<int> trang { get; set; }
        public bool cungCap { get; set; }
    
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public virtual tblNhaXB tblNhaXB { get; set; }
    }
}
